name: model_retraining_env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12.7
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - mlflow==2.19.0
      - joblib
      - matplotlib
      - seaborn
